### PR TITLE
login navigation

### LINKED ISSUE #156: Shelter Dashboard Login Navigation
**Describe the bug**
I was trying to see the Shelter Dashboard feature of this application. When I run the application locally and point my web browser to http://127.0.0.1:5000, I see a login for volunteer dashboard. When I log in using developer credentials: developer@slu.edu and any password, I end up in the Volunteer Dashboard of the application. If I change the URL to: http://localhost:3000/shelter-dashboard, I now see the Shelter Dashboard. However, there is no way for a user to directly log in to the shelter dashboard: the default page only has a login for the volunteer dashboard.

**To Reproduce**
1. Run the application locally with: docker-compose up
2. Point your web browser to http://127.0.0.1:5000 - this shows a login to a volunteer dashboard. There is no separate login to shelter dashboard
3. Log in using developer@slu.edu and any password you want
4. See that you are in a Volunteer Dashboard
5. Change the URL to http://localhost:3000/shelter-dashboard. You are now in the shelter dashboard

**Expected behavior**
I would expect that in step 3 of the process described above, there should be a Shelter login option. After logging in as a "shelter", I should see the shelter dashboard.

I'm open to suggestions for how to accomplish this. Here's an idea I'm proposing:
1. The landing page gives two options: Volunteer and Shelter Administrator
2. Based on the option the user selects, they are taken to the appropriate login page. The actual login component would be the same, but there would be a parameter or some kind of flag indicating if this is a volunteer or shelter admin logging in. This page has an option for them to switch view, with something like "Are you looking for Volunteer Dashboard?".
3. Once the user submits correct login credentials, they are taken to the appropriate dashboard (volunteer or shelter, based on the selection they made).

### PR DESCRIPTION
**Pull request by amalrzv**
Fixes #156 

**What was changed?**
Created HomeDashboard.js and HomeDashboard.css, changed App.js. HomeDashboard.js what created as a page that holds either role (volunteer or shelter admin) to then navigate to its respective login. App.js was modified to adjust routes for navigation. Created ShelterLogin.js based on Volunteer's Login.js  so that shelter admin can login once button is clicked on HomeDashboard.  Adjusted the route's in App.js accordingly. 

*Here, describe the issue that you are fixing with this code, and why your code fixes it.*
The codebase didn't have a login for shelter admin, which was added. Additionally, the app wasn't routed to the new homedashboard, so once that was created along with its respective styling, that was routed. 

**How was it changed?**

*Here, get into detail about what files you modified, and talk about the most important lines in regards to fixing the issue.*

**Screenshots that show the changes (if applicable):**
Screenshot 2025-02-03 at 1 42 44 PM
Screenshot 2025-02-03 at 1 43 01 PM

### CODE REVIEW

File: client_app/src/App.js [hunk 1]
```diff
@@ -28,7 +30,9 @@ function App() {
           <NavBarVolunteerDashboard auth={auth} />
         )}
         <Routes>
-          <Route path="/" element={<Login setAuth={setAuth} />} />
+          <Route path = "/" element={<HomeDashboard />} />
+          <Route path="/volunteer-login" element={<Login setAuth={setAuth} />} />
+          <Route path="/shelter-login" element={<ShelterDashboard />} />
```
Comment (amalrzv) [inline client_app/src/App.js:35]: Not sure why the homedashboard is laying over the volunteer dashboard

File: client_app/src/App.js [hunk 2]
```diff
@@ -14,24 +14,34 @@ import RequestForHelp from "./components/shelter/RequestForHelp";
 import { ShiftDetails } from "./components/shelter/ShiftDetails";
 import UpcomingRequests from "./components/shelter/UpcomingRequests";
 import "./styles/App.css";
+import HomeDashboard from "./components/HomeDashboard";
+import ShelterLogin from "./components/authentication/ShelterLogin";
+
+//import { BrowserRouter as Navigate } from "react-router-dom";
```
Comment (emrameduseljac) [inline client_app/src/App.js:20]: I would suggest leaving out commented out code

**Review by emrameduseljac — COMMENTED** [review]
The code looks clean and you did a good job of getting it submitted. Using the volunteer login page appears to be working perfectly, however after clicking the Shelter Dashboard login and entering the developer credentials, it takes you back to the main login page. This is the only bug/issue I came across, the volunteer version seems to be working perfectly.

File: client_app/src/App.js (hunk 2 above)
Comment (Taktar) [reply client_app/src/App.js:20]: I agree with Emra. However, I can definitely see how commenting out would be beneficial so that you can have something to look back at quickly in case you decide to keep that line of code.

Comment (amalrzv) [reply client_app/src/App.js:20]: Will do! I'll have that removed by the completion of the sprint.

File: client_app/src/App.js [hunk 3]
```diff
@@ -14,24 +14,34 @@ import RequestForHelp from "./components/shelter/RequestForHelp";
...
           <NavBarShelterDashboard auth={auth} />
         ) : (
           <NavBarVolunteerDashboard auth={auth} />
         )}
         <Routes>
-          <Route path="/" element={<Login setAuth={setAuth} />} />
+          <Route index element={<HomeDashboard />} />
+          <Route path="/home" element={<HomeDashboard />} />
+          <Route path="/volunteer-login" element={<Login setAuth={setAuth} />} />
+          <Route path="/shelter-login" element={<ShelterLogin setAuth={setAuth} />} />
```
Comment (Taktar) [inline client_app/src/App.js:40]: I like how this was added to ensure better separation of concerns and make it easier to manage route-specific components.

File: client_app/src/App.js [hunk 4]
```diff
@@ -14,24 +14,34 @@ import RequestForHelp from "./components/shelter/RequestForHelp";
...
 import UpcomingRequests from "./components/shelter/UpcomingRequests";
 import "./styles/App.css";
+import HomeDashboard from "./components/HomeDashboard";
+import ShelterLogin from "./components/authentication/ShelterLogin";
+
+//import { BrowserRouter as Navigate } from "react-router-dom";
 
 function App() {
-  const [auth, setAuth] = useState(false);
+  const [auth, setAuth] = useState(!!localStorage.getItem("token"));
```
Comment (Taktar) [inline client_app/src/App.js:23]: This ensures that if a user is logged in (i.e., has a valid token stored), they remain logged in even after refreshing the page or reopening the browser. This change is helpful because no regular user or admin would want to constantly log in repeatedly.

**Review by Taktar — COMMENTED** [review]
left a few different comments.

File: client_app/src/App.js [hunk 5]
```diff
@@ -14,24 +14,34 @@ import RequestForHelp from "./components/shelter/RequestForHelp";
...
         ) ? (
           <NavBarShelterDashboard auth={auth} />
         ) : (
           <NavBarVolunteerDashboard auth={auth} />
         )}
         <Routes>
-          <Route path="/" element={<Login setAuth={setAuth} />} />
+          <Route index element={<HomeDashboard />} />
+          <Route path="/home" element={<HomeDashboard />} />
+          <Route path="/volunteer-login" element={<Login setAuth={setAuth} />} />
```
Comment (amalrzv) [inline client_app/src/App.js:39]: Realized I'm only running the client component so I couldn't see that volunteer dashboard was working as expected, still having an with shelterdashboard as its not functioning properly

**Review by kate-holdener — CHANGES_REQUESTED** [review]
@amalrzv Nice job defining the login navigation. Please see my inline comments. 
Also, there are a couple of UI changes that I think would be nice.

1. On the main login screen, the navigation bar shows Volunteer Dashboard (on the left) and (sign in/sign up) on the right. This is a bit confusing for the user, because the main page directs them to Volunteer or Shelter sign in.
Screenshot 2025-02-04 at 10 24 11 AM

On the Shelter sign in page, there is also the Volunteer Dashboard and sign in/sign up in the nav bar, which is confusing for the user. It would be good to give the user an option to switch roles, if they realize they are on the wrong page. See screenshot below.
Screenshot 2025-02-04 at 10 25 58 AM

On the Volunteer sign in page, the Volunteer Dashboard and sign-in/sign-up options in the nav bar are also present. It would be good to communicate that this is volunteer sign up and give the user an option to switch role to admin. See screenshot below.
Screenshot 2025-02-04 at 10 27 22 AM

I know your Docker desktop is currently broken and you are running the client side outside of docker. You can start the server side to test the login functionality:
1. Navigate to the server directory
2. Create a python virtual environment: python3 -m venv venv
3. Activate the virtual environment: source venv/bin/activate
4. Install dependencies: pip3 install -r requirements.txt
5. Run the server-side: bash run_dev_server.sh

File: client_app/src/components/HomeDashboard.js [hunk 6]
```diff
@@ -0,0 +1,31 @@
...
+
+    useEffect(() => {
+        if (token) {
+          navigate("/dashboard"); // trying to fix redirecting issue 
+        }
+      }, [token, navigate]);
+
+    return(
+      <div className = "home-dashboard">
+        <h1>Shelter Volunteer Main System</h1>
```
[the remark this answers is not in the document]
Comment (amalrzv) [reply client_app/src/components/HomeDashboard.js:18]: Will change, thank you for the suggestion!

File: client_app/src/components/authentication/ShelterLogin.js [hunk 7]
```diff
@@ -0,0 +1,89 @@
+import { useState } from "react";
+import { Link, Navigate, useNavigate } from "react-router-dom";
+import { SERVER } from "../../config";
+import { Form, Button, Container, Card, Col, Row, FloatingLabel } from "react-bootstrap";
+import About from "../About";
+
+async function LoginShelterAdmin(username, password) {
+  try {
+    const response = await fetch(`${SERVER}/shelter-login`, {
```
[the remark this answers is not in the document]
Comment (amalrzv) [reply client_app/src/components/authentication/ShelterLogin.js:9]: Sounds good, will keep the same API

File: client_app/src/components/authentication/ShelterLogin.js
[the remark this answers is not in the document]
Comment (amalrzv) [reply client_app/src/components/authentication/ShelterLogin.js:1]: Thank you for this suggestion, Ill parameterize the original login and delete the repetitive code

File: client_app/src/components/authentication/ShelterLogin.js [hunk 8]
```diff
@@ -0,0 +1,89 @@
...
+        password: password,
+      }),
+    });
+
+    if (!response.ok) {
+      throw new Error(`HTTP error! Status: ${response.status}`);
+    }
+
+    const data = await response.json();
+    localStorage.setItem("shelterToken", JSON.stringify(data.access_token));
```
[the remark this answers is not in the document]
Comment (amalrzv) [reply client_app/src/components/authentication/ShelterLogin.js:25]: That makes sense, I realized since I wasn't running the server that anything I change in the code wouldn't appear, so this was part of one of the attempts before I realized the server issue. I'll get rid of this.

File: client_app/src/components/authentication/ShelterLogin.js (hunk 7 above)
[the remark this answers is not in the document]
Comment (amalrzv) [reply client_app/src/components/authentication/ShelterLogin.js:9]: Will change to the suggested change, thanks!

**Review by kate-holdener — CHANGES_REQUESTED** [review]
@amalrzv There is a warning from the linter about unused variable. That same unused variable results in a warning when I start up the client side app:
```
frontend-1              | Compiled with warnings.
frontend-1              | 
frontend-1              | [eslint] 
frontend-1              | src/components/HomeDashboard.js
frontend-1              |   Line 8:11:  'token' is assigned a value but never used  no-unused-vars
```
I think it's safe to just remove that variable and this PR will be ready for a merge. 
We can get the navbar cosmetic changes in later, in a different issue.

File: client_app/src/components/HomeDashboard.js [hunk 9]
```diff
@@ -0,0 +1,47 @@
+import "./../styles/HomeDashboard.css";
+import {useNavigate} from "react-router-dom"; 
+import { useEffect } from "react";
+
+
+function HomeDashboard() {
+    const navigate = useNavigate(); 
+    const token = localStorage.getItem("token");
```
[the remark this answers is not in the document]
Comment (amalrzv) [reply client_app/src/components/HomeDashboard.js:8]: Yes! I meant to remove that, thank you!

File: client_app/src/App.js [hunk 10]
```diff
@@ -14,25 +14,34 @@ import RequestForHelp from "./components/shelter/RequestForHelp";
...
-  const [auth, setAuth] = useState(false);
+  const [auth, setAuth] = useState(!!localStorage.getItem("token"));
+  const role = localStorage.getItem("role");
+
   return (
     <>
       <Router>
-        {["/shelter-dashboard", "/shift-details", "/request-for-help", "/upcoming-requests"].includes(
+        {["/home", "/"].includes(window.location.pathname) ? null : 
+        ["/shelter-dashboard", "/shift-details", "/request-for-help", "/upcoming-requests"].includes(
```
Comment (kate-holdener) [inline client_app/src/App.js:28]: I think this is the reason the nav bar is missing sometimes. Your logic makes sense, but I think react is not quite doing what we want it to do.

Comment (amalrzv) [reply client_app/src/App.js:28]: I see what you're saying, the reason i modified it was because the volunteer dashboard nav bar was showing up before a user logged in, so i had to adjust it.

**Review by kate-holdener — APPROVED** [review]
Beautifully done!
