### PR TITLE
issue402

### LINKED ISSUE #402: View Profile navigation fails after page change + profile route returns 404
Description

Describe the bug
On the volunteer dashboard, clicking “View Profile” in the user menu sometimes fails to navigate to the profile page after switching between pages without a full refresh.

Additionally, /volunteer/profile returns a 404 when no profile exists, and repeated API calls are triggered on load.

To Reproduce

Go to volunteer dashboard (e.g., Sign Up to Help)
Click on “View Profile” → works initially
Navigate to another page (e.g., Upcoming Shifts)
Click “View Profile” again
URL/page does not update unless refreshed
Expected behavior
“View Profile” should always navigate to /volunteer-dashboard/profile
Profile route should not return 404 when profile is missing
No repeated API calls on load

**Screenshots**

Desktop (please complete the following information):
OS: Windows 10
Browser: Chrome
Version: 147

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by dKhurshid**
Fixes #402 
What was changed?
Updated the volunteer web app (React client) and minor Flask API logic for profiles.

Client:
  Fixed “View Profile” navigation and menu behavior
  Synced dashboard state with URL
  Improved sidebar navigation + active tab highlighting
  Reduced duplicate API calls (profile + shift data)
  Improved profile modal behavior
  Fixed header/dropdown stacking (z-index)
  Server:
  /volunteer/profile now returns 200 with empty data instead of 404
  Removed debug logging in shelter serializer

Why was it changed?
  “View Profile” sometimes failed after navigation due to state/route mismatch and menu unmounting
  Profile endpoint returning 404 caused UI confusion
  Excess API calls from effect dependencies
  Dropdown layering issues affected usability
  Profile modal behavior needed to be more consistent
How was it changed?
  Synced dashboard state with location.pathname
  Used navigate() directly for reliable routing
  Removed unnecessary navigation side-effects in sidebar
  Deduplicated profile API calls (single in-flight request)
  Fixed data loading logic on shift signup page
  Updated backend to safely handle missing profiles
  Adjusted modal logic to avoid redundant navigation
**Screenshots that show the changes (if applicable):**

### CODE REVIEW

File: client_app/src/components/volunteer/ShiftSignUp.js [hunk 1]
```diff
@@ -45,24 +45,32 @@ function VolunteerShiftSignup(){
   const filterHintId = useId();
   const [dateFieldFocused, setDateFieldFocused] = useState(false);
   const user = getUser();
+
```
Comment (Supraja050202) [inline client_app/src/components/volunteer/ShiftSignUp.js:59]: Potential infinite re-render loop:
 `loadShiftPageData` is a dependency but is recreated via useCallback, causing this effect to re-run on every render.
 This can trigger repeated API calls after state updates (e.g., sign-up). Consider removing it from dependencies ([]) or stabilizing the function reference.

File: client_app/src/components/volunteer/IncompleteProfileModal.js [hunk 2]
```diff
@@ -1,22 +1,29 @@
...
 /**
  * Modal component that appears when a volunteer logs in with an incomplete profile.
  * Prompts the user to complete their profile information (firstName, lastName, phone).
  */
+const PROFILE_PATH = "/volunteer-dashboard/profile";
+
 const IncompleteProfileModal = ({ isOpen, onClose, onNavigateToProfile }) => {
   const navigate = useNavigate();
+  const location = useLocation();
+  const alreadyOnProfile = location.pathname === PROFILE_PATH;
```
Comment (Supraja050202) [inline client_app/src/components/volunteer/IncompleteProfileModal.js:16]: UX issue: If user is already on profile page,clicking "Complete Profile" silently does nothing.
Consider disabling the button or showing a message instead.

**Review by Supraja050202 — CHANGES_REQUESTED** [review]
The PR is generally well-structured with clear separation of concerns and good use of React hooks, but it introduces a critical risk of infinite re-renders due to an unstable useEffect dependency.
API calls and state updates are handled cleanly, though the data-loading logic should be better memoized or scoped to avoid repeated executions.
There is also a UX inconsistency in the profile completion modal where user actions can fail silently, reducing clarity and usability.
Overall, solid progress, but addressing the effect dependency issue and improving user feedback will significantly strengthen reliability and user experience.

File: client_app/src/components/volunteer/ShiftSignUp.js (hunk 1 above)
Comment (dKhurshid) [reply client_app/src/components/volunteer/ShiftSignUp.js:59]: Fixed

File: client_app/src/components/volunteer/IncompleteProfileModal.js (hunk 2 above)
Comment (dKhurshid) [reply client_app/src/components/volunteer/IncompleteProfileModal.js:16]: Fixed

**Review by Supraja050202 — APPROVED** [review]
Approved
